# Generated by Django 3.0.1 on 2022-10-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('date', models.DateTimeField()),
                ('time', models.TimeField()),
                ('turbidity', models.FloatField()),
                ('salinity', models.FloatField()),
                ('temperature', models.FloatField()),
            ],
        ),
    ]
